### PR TITLE
Add code of conduct link to footer

### PR DESCRIPTION
**Pull request by LizzHale**
This PR adds the code of conduct link to the footer. I wasn't entirely sure how we wanted this to look but figured it was best to throw something up and discuss in the PR. I looked around at how other websites handle this. [Devopsdays](https://www.devopsdays.org/) links to theirs with a sign-post icon in the footer:

screen shot 2016-09-24 at 10 23 46 am

Whereas [Railsbridge](railsbridge.org), explicitly mentions their code of conduct in the description of the org: 

screen shot 2016-09-24 at 10 28 43 am

Since the current footer doesn't have an obvious place to put the code of conduct, I chose to create an icon similar to the facebook and twitter icons to link externally to the [google doc](https://docs.google.com/document/d/16LUxODmHN3N2r4GPA-YeNgXP0MIQCl6gW_twJralb5w). 

screen shot 2016-09-24 at 10 22 32 am

The icon itself can be changed -- this was just a quick demo. Is there any iconography that immediately reads "code of conduct"? My hesitation with the icon strategy is that it's not immediately discoverable. 

/cc @MichelleGlauser

### CODE REVIEW

**Comment by MichelleGlauser** [comment]
Ooooh, great research and ideas! What if we used a scroll icon, like something people sign? Maybe[ the one with a heart on The Noun Project](https://thenounproject.com/Stephen_Plaster/collection/the-scroll-collection/?oq=scroll&cidx=1)?

**Comment by LizzHale** [comment]
> Ooooh, great research and ideas! What if we used a scroll icon, like something people sign? Maybe the one with a heart on The Noun Project?

I love that! To use royalty free, the icons are $1.99 - I'm happy to pay for this myself (otherwise, we need to hyperlink to source or credit underneath the icon which would be pretty busy in the footer). I'll end up modifying it so that it is similar to the other two icons (blue background, transparent fill) which I think is fine to do.

**Comment by LizzHale** [comment]
Updated the PR with the new icon: 

screen shot 2016-09-24 at 12 40 34 pm

**Comment by LizzHale** [comment]
I noticed that the other icons have a white fill counterpart so I added one in f59c316 for the code of conduct in case it's needed in the future.

**Comment by MichelleGlauser** [comment]
Awww, thank you! I can totally reimburse you if you'll let me know PayPal or Venmo info. This looks great!

**Comment by LizzHale** [comment]
> I can totally reimburse you if you'll let me know PayPal or Venmo info.

Thanks for the offer but I'm happy to purchase it. :smile: 

It wasn't totally clear from the README what the process for merging and deploying was so I'll hand this over.

**Pull request merged**
