### PR TITLE
Added 'we're not discriminate by age.' to what-we-do p.

### PR DESCRIPTION
**Pull request by shioramen**
Pull Request for adding an age free sentence to what-we-do <p>.

### CODE REVIEW

**Comment by shioramen** [comment]
Added YouTube link at the bottom.

**Comment by hagata** [comment]
Thanks, @shioramen 
The color is just a little bit off. Can you please update it to `#0093b5`?

**Comment by hagata** [comment]
The color is a tad bit off, still. Sorry about that. 

You can use this one.

youtube

**Comment by shioramen** [comment]
Hi Genki,

Sorry about the color discrepancy. I used the online editor and color picker but it wasn’t accurate enough. May I ask what photo editor that you used for color adjusting?

Esther.

**Comment by hagata** [comment]
Hi, Esther!
No problem, it happens 😄 
I used Photoshop for this one, but typically for these kinds of graphics, I'll use Illustrator and export SVG's.

**Comment by shioramen** [comment]
I see. 
Thanks Genki.

Esther.

**Pull request merged**
