### PR TITLE
News

### PR DESCRIPTION
**Pull request by brifinn**
This PR adds a news page to address #134. Michelle added a couple more requirements by email:
- The link to the news page should be a newspaper icon in the bottom nav
- The page should include a contact link and a link to logos

This is a rough cut right now. Everything functions, and looks okay on a variety of screen sizes. I haven't yet adequately tested across browsers, and won't bother updating sitemap.xml correctly until I'm ready to merge. I have a couple more questions:

- @MichelleGlauser, do you have any press releases to add? If the list may occasionally be empty, I'll add some placeholder text. If the releases are generally more than a couple paragraphs, I'll switch to a column layout to conserve space. 
- I borked the formatting in style.css when I rendered it from style.scss. I'm using ruby sass 3.4.23 with expanded style, which looks the closest to the original formatting. Is there some magic I have to do to fit the repo's style?

### CODE REVIEW

**Comment by MichelleGlauser** [comment]
Thank you! I'll email a couple of recent press releases. 

I'm using [the normal sass 1.15.2](https://sass-lang.com/install). 

Looks like the "In other media" <h2> isn't showing up for me. 
screen shot 2018-12-31 at 11 58 48 am

**Comment by brifinn** [comment]
Thanks! I will adjust the layout to better suit the press releases. I'll
look for the disappearing header. I may reach out 1:1 if I can't find it
right away.

Github's web UI is down right now, so I'll post a PR when it's back up.

**Comment by brifinn** [comment]
Awesome, thanks!

Michelle Glauser (she/her)
Techtonica Founder & CEO
Website <http://techtonica.org/> | Twitter
<http://twitter.com/TechtonicaOrg> | Facebook
<http://facebook.com/Techtonica> | LinkedIn
<https://www.linkedin.com/company/techtonica/> | (Nonprofit Tax ID:
46-1323531) <http://techtonica.org/donate>

**Comment by MichelleGlauser** [comment]
This looks excellent. Merging now.

**Pull request merged**
