### PR TITLE
Use Dotenv File to Store Secrets

### PR DESCRIPTION
**Pull request by gsong**
## How It Works

We use [python-dotenv][] to load a `.env` file on start up of the app. This
will ensure that the app context has whatever environment variable specified in
the `.env` file be part of `os.environ` (or `os.getenv`).

Place the `.env` file in the directory where the `passenger_wsgi.py` file is
located, since this is where the process root is. For example, for staging, the
`.env` file is located in `/home/techtonica/staging.techtonica.org/`.

### For Development

Be sure to create a `.env` file in the project root when doing development.
Don't worry, `.env` is Git ignored.

## Why Didn't It Work Before?

Previously, the `EVENTBRITE_OAUTH_TOKEN` environment variable was being set on
activation of the virtualenv. However, `passenger_wsgi` *does not* activate the
virtualenv at all, so the environment variable was never set.

[python-dotenv]: https://github.com/theskumar/python-dotenv

### CODE REVIEW

**Comment by vegetabill** [comment]
@gsong this is a good solution but shouldn't an encrypted version of `.env` be included in the repo? As it currently is implemented, contributors can't even boot the app locally.

**Comment by gsong** [comment]
@vegetabill How would having an encrypted version be safe? How would you use that?

**Comment by vegetabill** [comment]
It's easier to share a key than an entire config file so it's a very common way of securing config.

At the very least, the README should cover who owns the `.env` file and where authorized users can obtain it.

I'm working on another PR right now so that loading Eventbrite is optional locally, which might make this moot anyway.

**Comment by vegetabill** [comment]
see https://github.com/Techtonica/techtonica.org/pull/166

**Comment by gsong** [comment]
There's only a single secret right now, so that seems like an unnecessary overhead to me.

I agree re: documentation and skipping missing configs if it's not needed.

**Pull request merged**
